imports:
    - { resource: config_prod.yml }

web_profiler:
    toolbar: true
    intercept_redirects: false

ewz_recaptcha:
    enabled: false

twig:
    globals:
        rooturi: https://www.galeria-kaufhof.de/goodbuy-metro-preprod
