# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: @AppBundle/Resources/config/services.yml }

parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    kernel.listener.response_listener:
        class: AppBundle\Listener\ResponseListener
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
